version: '3.8'

services: 
  open-webui:
    build: web-ui/.
    container_name: open-webui
    ports:
      - "3000:8080"
    
    restart: always
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=ollama-server
  
  ollama-server:
    restart: always
    build: ollama-server/.

volumes:
  open-webui:
