# FROM ubuntu:latest
FROM ollama/ollama
# run apt update 
# run apt upgrade -y
# run apt install curl -y
# run apt install systemctl -y
EXPOSE 11434
# run systemctl start ollama
# run mkdir /home/ollama
# workdir /home/ollama
# copy ollama.sh  /home/ollama
# run ls -la
# run curl -fsSL https://ollama.com/install.sh | sh && systemctl start ollama && ollama pull llama2 
# run  echo "ollama serve && ollama pull llama2" > start
# run ls -la 
# cmd ["bash", "./start"]
# cmd ["ollama", "run", "llama2"]
